/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.*;
import Estructuras.*;

import static edd.proyecto2_201801229.EDDProyecto2_201801229.tablaHash;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.mavl;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author l4kz4
 */
public class Catologo extends javax.swing.JFrame {

    /**
     * Creates new form Catologo
     */
    DefaultTableModel model = new DefaultTableModel();
    Usuario usuarioActual = new Usuario();
    ArrayList<Libro> libros = new ArrayList<Libro>();
    public Catologo(Usuario actual) {
        initComponents();
        usuarioActual = actual;
        libros = mavl.todosLosLibros();
        cargaDeDatos();
        cargaItem();
    }
    
    public void cargaDeDatos(){
        model = new DefaultTableModel();
        model.addColumn("ISBN");
        model.addColumn("Titulo");
        model.addColumn("Autor");
        model.addColumn("Editorail");
        model.addColumn("Año");
        model.addColumn("Edicion");
        model.addColumn("Categoria");
        model.addColumn("Idioma");
        model.addColumn("Carnet Usuario");
        
        for (Libro libro:libros) {
            if (libro!=null) {
                Object[] dato = new Object[]{libro.getISBN(),libro.getTitulo(),
                libro.getAutor(),libro.getEditorial(),libro.getAño(),
                libro.getEdicion(),libro.getCategoria(),libro.getIdioma(),
                libro.getCarnetUsuario()};
                model.addRow(dato);
            }
        }
        
        jTable1.setModel(model);
    }
    
    public void cargaItem(){
        ArrayList<String> catalogo = mavl.iniciarCatalogo();
        jComboBox1.addItem("Todas");
        for (String categoria:catalogo) {
            if (categoria!=null) {
                jComboBox1.addItem(categoria);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 260, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 680, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Biblioteca bi  = new Biblioteca(usuarioActual);
        bi.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        try{
            String categoria = jComboBox1.getSelectedItem().toString();
            if (categoria.equals("Todas")) {
                libros = mavl.todosLosLibros();
            }else{
                libros = mavl.todosLosLibrosCategoria(categoria);
            }
            cargaDeDatos();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,
                "Error: "+ex,
                "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
