/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.*;
import Estructuras.*;

import static edd.proyecto2_201801229.EDDProyecto2_201801229.tablaHash;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.mavl;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.bloques;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.red;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.cb;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.nodoRed;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author l4kz4
 */
public class DarBaja extends javax.swing.JFrame {

    /**
     * Creates new form DarBaja
     */
    DefaultTableModel model = new DefaultTableModel();
    Usuario usuarioActual = new Usuario();
    ArrayList<Libro> libros = new ArrayList<Libro>();
    public DarBaja(Usuario actual) {
        initComponents();
        usuarioActual = actual;
        libros = mavl.todosLosLibros();
        cargaDeDatos();
    }

    public void cargaDeDatos(){
        model = new DefaultTableModel();
        model.addColumn("ISBN");
        model.addColumn("Titulo");
        model.addColumn("Autor");
        model.addColumn("Editorail");
        model.addColumn("Año");
        model.addColumn("Edicion");
        model.addColumn("Categoria");
        model.addColumn("Idioma");
        model.addColumn("Carnet Usuario");
        
        for (Libro libro:libros) {
            if (libro!=null) {
                Object[] dato = new Object[]{libro.getISBN(),libro.getTitulo(),
                libro.getAutor(),libro.getEditorial(),libro.getAño(),
                libro.getEdicion(),libro.getCategoria(),libro.getIdioma(),
                libro.getCarnetUsuario()};
                model.addRow(dato);
            }
        }
        
        jTable1.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 200, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, -1));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 690, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Biblioteca bi  = new Biblioteca(usuarioActual);
        bi.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try{
            int ISBN = Integer.parseInt(jTextField1.getText());
            Libro borrado = mavl.iniciarEliminar(ISBN, usuarioActual.getCarnet());
            if (borrado!=null) {
                 JOptionPane.showMessageDialog(null,
                "El libro fue borrado con exito \nISBN: "+borrado.getISBN()
                +"\nTitulo: "+borrado.getTitulo()
                +"\nCarnet Uusario: "+borrado.getCarnetUsuario(),
                "Libro",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,
                "No se ha encontrado el libro o no le pertenece",
                "ADVERTENCIA!!!",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,
                "Error: "+ex,
                "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
        }
        jTextField1.setText("");
        libros = mavl.todosLosLibros();
        cargaDeDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String titulo = jTextField1.getText();
            if (titulo.equals("")) {
                libros = mavl.todosLosLibros();
                cargaDeDatos();
            }else{
                libros = mavl.busquedaTitutlo(titulo);
                cargaDeDatos();  
            }
        }catch(Exception ex){
             JOptionPane.showMessageDialog(null,
                "Error: "+ex,
                "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
        }
        
        jTextField1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
