/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.*;
import Estructuras.*;

import static edd.proyecto2_201801229.EDDProyecto2_201801229.tablaHash;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.mavl;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.bloques;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.red;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.cb;
import static edd.proyecto2_201801229.EDDProyecto2_201801229.nodoRed;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author l4kz4
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    Usuario usuarioActual = new Usuario();

    public Reportes(Usuario actual) {
        initComponents();
        usuarioActual = actual;
        cargaItem();
        jComboBox2.setVisible(false);
        jLabel1.setVisible(false);
    }

    public void cargaItem() {
        ArrayList<String> catalogo = mavl.iniciarCatalogo();
        for (String categoria : catalogo) {
            if (categoria != null) {
                jComboBox2.addItem(categoria);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arbol AVL: Categorias", "Arbol B: Libros", "Tabla Hash: Usuarios", "Lista Simple: Nodos", "Lista Doble: Bloques", "Recorrido Preorden: Categorias", "Recorrido Inorden: Categorias", "Recorrido Postorden: Categorias" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, -1));

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 120, 40));

        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Categoria:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Reporte:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 660, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Biblioteca bi = new Biblioteca(usuarioActual);
        bi.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        try {
            String categoria = jComboBox1.getSelectedItem().toString();
            if (categoria.equals("Arbol B: Libros")) {
                jComboBox2.setVisible(true);
                jLabel1.setVisible(true);
            } else {
                jComboBox2.setVisible(false);
                jLabel1.setVisible(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Error: " + ex,
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String categoria = jComboBox1.getSelectedItem().toString();
            if (categoria.equals("Arbol AVL: Categorias")) {
                mavl.graficarArbol();
                Image img = new ImageIcon("ArbolAVL.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            } else if (categoria.equals("Tabla Hash: Usuarios")) {
                tablaHash.graficar();
                Image img = new ImageIcon("TablaHash.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            } else if (categoria.equals("Arbol B: Libros")) {
                String cat = "";
                cat = jComboBox2.getSelectedItem().toString();
                AVLNode ca = mavl.buscar(cat);
                if (ca != null) {
                    mavl.graficarArbolB(ca);
                    Image img = new ImageIcon("ArbolB.png").getImage();
                    ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                    jLabel3.setIcon(img2);
                }
            } else if (categoria.equals("Lista Simple: Nodos")) {
                red.iniciarGrafica();
                Image img = new ImageIcon("Nodos.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            } else if (categoria.equals("Lista Doble: Bloques")) {
                bloques.iniciarGrafica();
                Image img = new ImageIcon("Bloques.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            } else if (categoria.equals("Recorrido Preorden: Categorias")) {
                mavl.GraficarPreorden();
                Image img = new ImageIcon("Preorden.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            }else if (categoria.equals("Recorrido Inorden: Categorias")) {
                mavl.GraficarInorden();
                Image img = new ImageIcon("Inorden.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            }else if (categoria.equals("Recorrido Postorden: Categorias")) {
                mavl.GraficarPostorden();
                Image img = new ImageIcon("Postorden.png").getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));
                jLabel3.setIcon(img2);
            }

            //Tabla Hash: Usuarios
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Error: " + ex,
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
